[package]
name = "openraft-memstore"
version = "0.6.6"
edition = "2021"
authors = [
    "Databend Authors <opensource@datafuselabs.com>",
    "Anthony Dodd <Dodd.AnthonyJosiah@gmail.com>"
]
categories = ["algorithms", "asynchronous", "data-structures"]
description = "An in-memory implementation of the `openraft::RaftStorage` trait."
documentation = "https://docs.rs/openraft-memstore"
homepage = "https://github.com/datafuselabs/openraft"
keywords = ["raft", "consensus"]
license = "MIT/Apache-2.0"
repository = "https://github.com/datafuselabs/openraft"
readme = "README.md"

[dependencies]
anyhow = "1.0.32"
anyerror = "0.1.6"
openraft = { version="0.6.6", path= "../openraft" }
async-trait = "0.1.36"
serde = { version="1.0.114", features=["derive"] }
serde_json = "1.0.57"
tokio = { version="1.0", default-features=false, features=["sync"] }
tracing = "0.1.29"
tracing-futures = "0.2.4"

[dev-dependencies]
maplit = "1.0.2"

[features]
docinclude = [] # Used only for activating `doc(include="...")` on nightly.

[package.metadata.docs.rs]
features = ["docinclude"] # Activate `docinclude` during docs.rs build.
