[package]
name = "actix-raft"
version = "0.1.0"
edition = "2018"
authors = ["Anthony Dodd <Dodd.AnthonyJosiah@gmail.com>"]
categories = ["Algorithms", "Asynchronous", "Database", "Raft"]
description = "An implementation of the Raft distributed consensus protocol using the Actix actor framework."
documentation = "https://docs.rs/actix-raft"
homepage = "https://github.com/railgun-rs/actix-raft"
keywords = ["raft", "consensus", "data-storage"]
license = "MIT/Apache-2.0"
repository = "https://github.com/railgun-rs/actix-raft"

[dependencies]
actix = "0.8"
bytes = "0.4"
futures = "0.1"
log = "0.4"
rand = "0.6"
serde = { version="1", features=["derive"] }
tokio-timer = "0.2"

[dev-dependencies]
async-log = "1"
env_logger = "0.6"
rmp = "0.8"
rmp-serde = "0.13"
tempfile = "3"

[features]
docinclude = [] # Used only for activating `doc(include="...")` on nightly.

[package.metadata.docs.rs]
features = ["docinclude"] # Activate `docinclude` during docs.rs build.
