[package]
name = "openraft-rocksstore-v2"
description = "A rocksdb based implementation of the `openraft::RaftStorage` trait."
documentation = "https://docs.rs/openraft-rocksstore"
readme = "README.md"

version = "0.1.0"
edition = "2021"
authors = [
    "drdr xp <drdr.xp@gmail.com>",
]
categories = ["algorithms", "asynchronous", "data-structures"]
homepage = "https://github.com/datafuselabs/openraft"
keywords = ["raft", "consensus"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/datafuselabs/openraft"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openraft = { path= "../../openraft", version = "0.9.0", features=["serde", "storage-v2"] }

rocksdb = "0.20.1"
rand = "*"
byteorder = "1.4.3"
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.57"
tracing = "0.1.29"

[dev-dependencies]
async-trait = { version = "0.1.36" }
tempfile = { version = "3.4.0" }

[package.metadata.docs.rs]
all-features = true
