[package]
name = "openraft-memstore"
description = "A in-memory implementation of the `openraft::RaftLogStorage` and `openraft::RaftStateMachine` trait."
documentation = "https://docs.rs/openraft-memstore"
readme = "README.md"

version       = { workspace = true }
edition       = { workspace = true }
authors       = { workspace = true }
categories    = { workspace = true }
homepage      = { workspace = true }
keywords      = { workspace = true }
license       = { workspace = true }
repository    = { workspace = true }

[dependencies]
openraft = { path = "../../openraft", version = "0.10.0", features = ["serde", "type-alias"] }

derive_more = { workspace = true }
futures     = { workspace = true }
serde       = { workspace = true }
serde_json  = { workspace = true }
tokio       = { workspace = true }
tracing     = { workspace = true }

[dev-dependencies]

[features]
bt = ["openraft/bt"]
single-term-leader = []

[package.metadata.docs.rs]
all-features = true
