[package]
name = "async-raft"
version = "0.5.0"
edition = "2018"
authors = ["Anthony Dodd <Dodd.AnthonyJosiah@gmail.com>"]
categories = ["algorithms", "asynchronous", "data-structures"]
description = "An async implementation of the Raft distributed consensus protocol."
documentation = "https://docs.rs/async-raft"
homepage = "https://github.com/railgun-rs/async-raft"
keywords = ["raft", "consensus", "data-storage"]
license = "MIT/Apache-2.0"
repository = "https://github.com/railgun-rs/async-raft"
readme = "README.md"

[dependencies]
async-trait = "0.1.36"
bytes = "0.5"
futures = "0.3"
log = "0.4"
rand = "0.7"
serde = { version="1", features=["derive"] }
thiserror = "1.0.20"
tokio = { version="0.2", default-features=false, features=["fs", "io-util", "macros", "rt-core", "stream", "sync", "time"] }
tracing = "0.1"
tracing-futures = { version="0.2.4", features=["tokio"] }

[dev-dependencies]
env_logger = "0.7"
rmp = "0.8"
rmp-serde = "0.14"
tempfile = "3"

[features]
docinclude = [] # Used only for activating `doc(include="...")` on nightly.

[package.metadata.docs.rs]
features = ["docinclude"] # Activate `docinclude` during docs.rs build.
