name: Release
on:
  push:
    tags:
      - "v*"
      - "!v*-alpha*"
      - "!v*-beta*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2

      - name: Setup | Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Publish openraft
        run: cd openraft && cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}

  # release:
  #   needs: publish
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Setup | Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0

  #     # save tag name in var "tag"
  #     - name: Extract tag
  #       id: vars
  #       run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

  #     - name: Build | Publish
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         body_path: change-log/${{ steps.vars.outputs.tag }}.md
  #         draft: true
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
